spring:
  application:
    name: fate-charsheet-server
  jackson:
    serialization-inclusion: non-null
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

---

spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

