version: "2"

services:
  web:
    image: fate.upliftinglemma.net/fate-charsheet-server:dev
    depends_on:
      - db
      - nginx
    links:
      - db
    volumes:
      - .:/opt/app:Z
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VIRTUAL_HOST=~fate.upliftinglemma.net,fate\.upliftinglemma\..*\.xip\.io

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    security_opt:
      - label:type:docker_t
