spring:
  application:
    name: fate-charsheet-server
  jackson:
    serialization-inclusion: non-null
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: 0

---

flyway:
  enabled: false
spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
