spring:
  application:
    name: fate-charsheet-server
  jackson:
    serialization-inclusion: non-null
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: 0

---

spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://db/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080

---

spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
flyway:
  enabled: false
server:
  port: 8080
